services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.vertexAI
    container_name: style-bert-vits2-vertexAI
    tty: true
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "5000:5000"