FROM python:3.10
RUN useradd -m -u 1000 user

USER user

ENV HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

RUN pip install --no-cache-dir --upgrade pip

COPY --chown=user . $HOME/app
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r $HOME/app/requirements.txt


# # 必要に応じて制限を変更してください
# CMD ["python", "server_editor_vertex.py"]